
[PhysicsEngine]

damping = 0.5

    [PhysicsEngine.Gravity]

    y = 10

[Scenario]

name = 'example2'
debug = true

[[Ship]]

id = 's1'
name = 'ship1'
model = 'examples/ship1'
controller = 'examples/ship1_control_example.py'

x = 50
y = 100
angle = 45

[[Ship]]

id = 's2'
name = 'ship2'
model = 'examples/ship1'
controller = 'examples/ship1_control_example.py'

x = 50
y = 100
angle = -45

[[Ship]]

id = 's3'
name = 'ship3'
model = 'examples/ship1'
controller = 'examples/ship1_control_example.py'

x = 200
y = 100

[[Object]]

model = '.object1'

x = 100
y = 100

[[Image]]

path = '.example.png'

x = -200
y = -200

height = 100
